TiendaAbarrotesLaravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\VentaController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [IndexController::class, 'index']);

Route::resource('/Lista_productos', ProductController::class);
Route::get('home/ventas', function(){
    return view('store.venta');
});
Route::get('home/stock', function(){
    return view('store.update');
});
Route::resource('productos', ProductController::class);
Route::resource('/stock',StockController::class);
Route::get('/ventas/efectivo', [VentaController::class, 'EfectivoIndex'], )->name('ventas.EfectivoIndex');
Route::post('/ventas/efectivo', [VentaController::class, 'EfectivoStore'])->name('ventas.EfectivoStore');
Route::get('/ventas/transferencia', [VentaController::class, 'TransferenciaIndex'], )->name('ventas.TransferenciaIndex');
Route::post('/ventas/transferencia', [VentaController::class, 'EfectivoStore'])->name('ventas.EfectivoStore');
Route::resource('/ventas', VentaController::class);

TiendaAbarrotesLaravel/resources/views/store/create.blade.php
@extends('layouts.layout')

@section('content')
<div class="container">
    <h1>Crear Producto</h1>
    <form action="{{ route('productos.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Nombre:</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="form-group">
            <label for="category_id">Categoría:</label>
            <select class="form-control" id="category_id" name="category_id" required>
                @foreach($categorias as $categoria)
                <option value="{{ $categoria->id }}">{{ $categoria->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="description">Descripción:</label>
            <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
        </div>
        <div class="form-group">
            <label for="price">Precio:</label>
            <input type="number" class="form-control" id="price" name="price" min="0" step="0.1" required>
        </div>
        <div class="form-group">
            <label for="stock">Stock:</label>
            <input type="number" class="form-control" id="stock" name="stock" min="0" required>
        </div>
        <div class="form-group">
            <label for="code">Código:</label>
            <input type="text" class="form-control" id="code" name="code" required>
        </div>
        <div class="form-group">
            <label for="image">Imagen:</label>
            <input type="file" class="form-control-file" id="image" name="image" accept="image/*" required>
        </div>
        <div class="form-group">
            <label for="expiration_date">Fecha de Vencimiento:</label>
            <input type="date" class="form-control" id="expiration_date" name="expiration_date" required>
        </div>
        <button type="submit" class="btn btn-primary">Crear Producto</button>
    </form>
</div>
@endsection

TiendaAbarrotesLaravel/resources/views/store/index_ta.blade.php
@extends('layouts.layout')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/styles_index.css') }}">
@endsection

@section('content')
    <div class="background-image">
        <div class="centered">
            <h1>Tienda de Abarrotes<br>"Doña Juana"</h1>
        </div>
    </div>
@endsection

TiendaAbarrotesLaravel/resources/views/store/lista_productos.blade.php
@extends('layouts.layout')

@section('styles')
<link rel="stylesheet" href="{{ asset('css/styles_lista_productos.css') }}">
@endsection

@section('content')
<div class="container">
        <div class="header">
            <h1>LISTA DE PRODUCTOS 2024</h1>
            <!-- <a href="{{ route('Lista_productos.create') }}" class="create-button">Crear</a> -->
        </div>
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Codigo</th>
                        <th>Stock</th>
                        <th>Precio</th>
                        <th>Categoria</th>
                        <!-- <th>Acciones</th> -->
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $producto)
                    <tr>
                        <td>{{ $producto->name }}</td>
                        <td>{{ $producto->code }}</td>
                        <td>{{ $producto->stock }}</td>
                        <td>{{ $producto->price }}</td>
                        <td>
                        @foreach ($categories as $category)
                            @if($producto->category_id == $category->id)
                                {{ $category->name }}
                            @endif
                        @endforeach
                        </td>
                        <!-- <td>
                            <div class="action-buttons">
                                <a href="{{ route('Lista_productos.edit', $producto->id) }}" class="edit-button">Editar</a> 
                                <button type="button" onclick="ConfirmDelete('{{ $producto->id }}')" class="delete-button">Eliminar</button>
                            </div>
                        </td> -->
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection


@section('scripts')
<script>
        function ConfirmDelete(id) {
            if(confirm('¿Estás seguro de que deseas eliminar este producto?')) {
                window.location.href = '/products/delete/' + id;
            }
        }
</script>
@endsection

TiendaAbarrotesLaravel/resources/views/store/pago_efectivo.blade.php
@extends('layouts.layout')

@section('styles')
<link rel="stylesheet" href="{{ asset('css/styles_efectivo.css') }}">
@endsection

@section('content')
<div class="factura-container">
    <form id="facturaForm" action="{{ route('ventas.EfectivoStore') }}" method="post">
        @csrf
        <h2>Factura</h2>
        <div class="productos">
            <ul>
                @foreach ($products as $product)
                <li>
                    <div>
                    {{ $product['nombre'] }} - Cantidad: {{ $product['cantidad'] }} - @if(isset($product['total_precio'])) Precio: {{ $product['total_precio'] }} @endif
                    </div>
                </li>
                @endforeach
            </ul>
        </div>
        <div class="total">
            <p>Total: {{ $totalPrice }}</p>
        </div>
        <button type="submit" class="pay-button">Pagar</button>
    </form>
    <button onclick="window.history.back()" class="back-button">Volver</button>
</div>
@endsection

TiendaAbarrotesLaravel/resources/views/store/pago_transferencia.blade.php
@extends('layouts.layout')

@section('styles')
<link rel="stylesheet" href="{{ asset('css/styles_transferencia.css') }}">
@endsection

@section('content')
<div class="transferencia-container">
    <h2 style="text-align: center;">Factura</h2>
    <div class="container-info">
        <div class="qr-code">
            <img src="{{ asset('content/imgs/photo_2024-02-28_03-38-42.jpg') }}" alt="Código QR" width="270px" height="300px"><br>
        </div>
        <div class="form">
            <form id="facturaForm" action="{{ route('ventas.EfectivoStore') }}" method="post">
                @csrf
                <div class="codigo-transferencia">
                    <label for="codigo">Código de transferencia:</label>
                    <input type="text" id="codigo" name="codigo" required>
                </div>
                <div class="productos-seleccionados">
                    <h3>Productos Seleccionados:</h3>
                    <ul>
                        @foreach ($products as $product)
                        <li>
                            <div>
                                {{ $product['nombre'] }} - Cantidad: {{ $product['cantidad'] }} - @if(isset($product['total_precio'])) Precio: {{ $product['total_precio'] }} @endif
                            </div>
                        </li>
                        @endforeach
                    </ul>
                </div>
                <div class="botones">
                    <button type="submit">Pagar</button>
                    <button onclick="window.history.back()">Volver</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

TiendaAbarrotesLaravel/resources/views/store/update.blade.php
@extends('layouts.layout')

@section('content')
<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
    }
</style>
<div class="container">
    <h1>Actualización de Stock</h1>
    @if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Stock</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $producto)
            <tr>
                <td>{{ $producto->id }}</td>
                <td>{{ $producto->name }}</td>
                <td>{{ $producto->stock }}</td>
                <td>
                    <form action="{{ route('stock.update', $producto->id) }}" method="POST" style="display: flex; align-items: center;">
                        @csrf
                        @method('PATCH')
                        <input type="hidden" name="producto_id" value="{{ $producto->id }}">
                        <input type="number" name="cantidad" value="0" min="0" id="cantidad-{{ $producto->id }}" class="form-control" style="width: 30px; margin-right: 5px;">
                        <button type="button" class="btn btn-primary" onclick="increment('{{ $producto->id }}')">+</button>
                        <button type="button" class="btn btn-primary" onclick="decrement('{{ $producto->id }}')">-</button>
                        <button type="submit" class="btn btn-success">Ingresar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

<script>
    function increment(id) {
        var input = document.getElementById('cantidad-' + id);
        input.value = parseInt(input.value) + 1;
    }

    function decrement(id) {
        var input = document.getElementById('cantidad-' + id);
        var value = parseInt(input.value) - 1;
        input.value = value < 0 ? 0 : value;
    }
</script>
@endsection

TiendaAbarrotesLaravel/resources/views/store/venta.blade.php
@extends('layouts.layout')

@section('styles')
<link rel="stylesheet" href="{{ asset('css/styles_venta.css') }}">
@endsection

@section('content')
<div class="read">
    <div class="venta">
        <h1 style="text-align: center; margin-top: 20px;">Ventas</h1>
        <form id="sellForm" action="" method="post">
            @csrf
            <label for="productName">Producto:</label>
            <input type="text" id="productName" name="productName" placeholder="Ingrese nombre o codigo de producto" required /><br /><br />
            <label for="amount">Cantidad:</label>
            <input type="number" id="amount" name="amount" placeholder="Ingrese cantidad" required /><br /><br />
            <button type="submit" class="button-vender">Agregar</button>
        </form>
    </div>

    <div class="pagos">
        <div class="pacientes">
            @foreach ($alert_products as $product)
            @if ($product->stock <= 10) 
            <div class="alert-container">
                <div class="alert">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';">×</span>
                    <p>
                        ¡Alerta! El producto {{ $product->name }} tiene niveles de
                        existencia bajos ({{ $product->stock }})
                    </p>
                </div>
            </div>
            @endif
            @endforeach
        </div>
        <div id="lista" class="lista">
            <h2>Productos Agregados:</h2>
            <ul>
                @foreach ($products as $product)
                <li>
                    <div class="list_button">
                        <div>
                            {{ $product['nombre'] }} - Cantidad: {{ $product['cantidad'] }} - @if(isset($product['total_precio'])) Precio: {{ $product['total_precio'] }} @endif
                        </div>
                    </div>
                </li>
                @endforeach
            </ul>
            <p>Total: {{ $totalPrice }}</p>
        </div>
        <h1 style="text-align: center;">Selección de Forma de Pago</h1>
        <div class="pagos_botones">
            <button onclick="window.location.href=`{{ route('ventas.EfectivoIndex') }}`">
                Pagar en Efectivo
            </button>
            <button onclick="window.location.href=`{{ route('ventas.TransferenciaIndex') }}`">
                Pagar por Transferencia
            </button>
        </div>

    </div>
</div>
@endsection


@section('scripts')
<script>
    document.getElementById("sellForm").addEventListener("submit", function(event) {
        setTimeout(function() {
            window.location.reload();
        }, 1000);
    });
</script>
@endsection