Final/Cursos-app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CursoController;
use App\Http\Controllers\TipoCursoController;
use App\Models\TipoCurso;

Route::resource('cursos', CursoController::class);
Route::resource('tipoCursos', TipoCursoController::class)->parameters([
    'tipoCursos' => 'tipoCurso'
]);
Route::get('/', [CursoController::class, 'index'])->name('home');

Final/Cursos-app/app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    use HasFactory;
    protected $fillable=['nombre','fecha_inicio','fecha_final','tipo_curso_id'];
    public function tipoCurso()
    {
        //relacion con el modelo ciudad          estandar
        return $this->belongsTo(TipoCurso::class, 'tipo_curso_id','id');
    }
}

Final/Cursos-app/app/Models/TipoCurso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TipoCurso extends Model
{
    use HasFactory;
    protected $table = 'tipo_cursos';
    protected $fillable = ['id','nombre'];
    public function cursos()
    {
        return $this->hasMany(Curso::class);
    }
}

Final/Cursos-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

Final/Cursos-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

Final/Cursos-app/app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Curso;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\TipoCurso;

class CursoController extends Controller
{

    public function index()
    {
        $cursos = Curso::with('tipoCurso')->get();
        return view('cursos.index', ['cursos' => $cursos]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $tipoCurso = TipoCurso::all();
        return view('cursos.create', ['tipoCurso' => $tipoCurso])->with('success', 'curso creadoq correctamente.');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //depurar y ver valores
        // dd($request->all());
        Curso::create($request->all());
        return redirect()->route('cursos.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Curso $curso)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Curso $curso)
    {
        // Muestra los valores del objeto
        // dd($participante);
        $tipoCurso = TipoCurso::all();
        return view('cursos.edit', ['curso' => $curso], ['tipoCurso' => $tipoCurso]);
    }


    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Curso $curso)
    {
        $curso->update($request->all());
        return redirect()->route('cursos.index')->with('success', 'curso actualizado correctamente.');
    }


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Curso $curso)
    {
        $curso->delete();

        return redirect()->route('cursos.index')->with('success', 'curso eliminado correctamente.');
    }
}

Final/Cursos-app/app/Http/Controllers/TipoCursoController.php
<?php

namespace App\Http\Controllers;

use App\Models\TipoCurso;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TipoCursoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(TipoCurso $tipoCurso)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(TipoCurso $tipoCurso)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, TipoCurso $tipoCurso)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(TipoCurso $tipoCurso)
    {
        //
    }
}

Final/Cursos-app/resources/views/cursos/create.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Curso</title>

</head>
<body>
    <h1>Crear Nuevo Curso</h1>

    <form action="{{ route('cursos.store') }}" method="POST">
        @csrf

            <label for="nombre">Nombre del Curso:</label>
            <input type="text" id="nombre" name="nombre" required>
            <br>
            <label for="fecha_inicio">Fecha de Inicio:</label>
            <input type="date" id="fecha_inicio" name="fecha_inicio" required>
            <br>
            <label for="fecha_final">Fecha de Finalización:</label>
            <input type="date" id="fecha_final" name="fecha_final" required>
            <br>

        <div>
            <label for="tipo_curso_id">Tipo de Curso:</label>
            <select id="tipo_curso_id" name="tipo_curso_id" required>
                <option value="" disabled selected>Selecciona un tipo de curso</option>
                @foreach($tipoCurso as $tipo)
                    <option value="{{ $tipo->id }}">{{ $tipo->nombre }}</option>
                @endforeach
            </select>
        </div>

        <button type="submit">Crear Curso</button>
    </form>
</body>
</html>

Final/Cursos-app/resources/views/cursos/edit.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Curso</title>
</head>

<body>
    <h1>Editar Curso</h1>

    <form action="{{ route('cursos.update', $curso->id) }}" method="POST">
        @csrf
        @method('PUT')
        <label for="nombre">Nombre</label>
        <input type="text" id="nombre" name="nombre" value="{{ $curso->nombre }}" required>

        <label for="fecha_inicio">Fecha Inicio</label>
        <input type="date" id="fecha_inicio" name="fecha_inicio" value="{{ $curso->fecha_inicio }}" required>

        <label for="fecha_final">Fecha Final</label>
        <input type="date" id="fecha_final" name="fecha_final" value="{{ $curso->fecha_final }}" required>

        <label for="tipo_curso_id">Tipo de Curso</label>
        <select id="tipo_curso_id" name="tipo_curso_id" required>
            @foreach($tipoCurso as $tipo)
                <option value="{{ $tipo->id }}" {{ $curso->tipo_curso_id == $tipo->id ? 'selected' : '' }}>{{ $tipo->nombre }}</option>
            @endforeach
        </select>

        <button type="submit">Actualizar</button>
    </form>
</body>

</html>

Final/Cursos-app/resources/views/cursos/index.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Cursos</title>
    <style>
        body {
            padding: 20px;
        }

        h1 {
            color: #333;
        }

        table {
            width: 50%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid black;
            text-align: left;
        }

    </style>
</head>

<body>
    


    <table>
    <h1>Lista de Cursos</h1>
    <br>
    <a href="{{ route('cursos.create') }}">Crear Nuevo Curso</a>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Fecha Inicio</th>
                <th>Fecha Final</th>
                <th>Tipo de Curso</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($cursos as $curso)
            <tr>
                <td>{{ $curso->id }}</td>
                <td>{{ $curso->nombre }}</td>
                <td>{{ $curso->fecha_inicio }}</td>
                <td>{{ $curso->fecha_final }}</td>
                <td>{{ $curso->tipoCurso->nombre }}</td>
                <td class="action-buttons">
                    <a href="{{ route('cursos.edit', $curso->id) }}">Editar</a>
                    <form action="{{ route('cursos.destroy', $curso->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit">Eliminar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>