Tareas/libreria/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EditorialController;
use App\Http\Controllers\LibroController;

Route::resource('libros', LibroController::class);
Route::resource('editoriales', EditorialController::class)->parameters([
    'editoriales' => 'editorial'
]);
Route::view('/', 'layout.main')->name('home');

Tareas/libreria/app/Models/Editorial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Libro;
class Editorial extends Model
{
    use HasFactory;
    protected $table = 'editorials';
    protected $fillable = ['id', 'nombre'];
    public function libros()
    {
        return $this->hasMany(Libro::class);
    }
}

Tareas/libreria/app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Editorial;

class Libro extends Model
{
    use HasFactory;
    protected $fillable = ['titulo', 'editorial_id', 'edicion', 'pais', 'precio'];
    public function editorial()
    {
        //relacion con el modelo ciudad          estandar
        return $this->belongsTo(Editorial::class, 'editorial_id', 'id');
    }
}

Tareas/libreria/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

Tareas/libreria/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

Tareas/libreria/app/Http/Controllers/EditorialController.php
<?php

namespace App\Http\Controllers;

use App\Models\Editorial;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class EditorialController extends Controller
{
    public function index()
    {
        $editoriales = Editorial::all();
        return view('editoriales.index',['editoriales'=>$editoriales]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('editoriales.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        Editorial::create($request->all());
        return redirect()->route('editoriales.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Editorial $editorial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Editorial $editorial)
    {
        return view('editoriales.edit',['editorial'=>$editorial]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Editorial $editorial)
    {
        $editorial->update($request->all());
        return redirect()->route('editoriales.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Editorial $editorial)
    {
        $editorial->delete();
        return redirect()->route('editoriales.index'); 
    }
}

Tareas/libreria/app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Libro;
use App\Http\Controllers\Controller;
use App\Models\Editorial;
use Illuminate\Http\Request;

class LibroController extends Controller
{

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $libros = Libro::with('editorial')->get();
        return view('libros.index', ['libros' => $libros]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $editoriales = Editorial::all();
        return view('libros.create', ['editoriales' => $editoriales]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //depurar y ver valores
        // dd($request->all());
        Libro::create($request->all());
        return redirect()->route('libros.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Libro $libro)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Libro $libro)
    {
        // Muestra los valores del objeto
        $editoriales = Editorial::all();
        return view('libros.edit', ['libro' => $libro], ['editoriales' => $editoriales]);
    }


    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Libro $libro)
    {
       $libro->update($request->all());
        return redirect()->route('libros.index');
    }


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Libro $libro)
    {
        // Elimina el participante de la base de datos
        $libro->delete();

        // Redirecciona a la página index con un mensaje de éxito
        return redirect()->route('libros.index')->with('success', 'libro eliminado correctamente.');
    }
}

Tareas/libreria/resources/views/editoriales/create.blade.php
@extends('layout.main')

@section('content')
    <form action="{{ route('editoriales.store') }}" method="post">
        @csrf
        <label for="nombre">nombre</label>
        <input type="text" name="nombre">
        <br>
        <button type="submit">Guardar</button>
    </form>
@endsection

Tareas/libreria/resources/views/editoriales/edit.blade.php
@extends('layout.main')

@section('content')
    <h1>Editar editorial</h1>

    <form action="{{ route('editoriales.update', $editorial->id) }}" method="POST">
        @csrf
        @method('PUT')

        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" id="nombre" value="{{ $editorial->nombre }}">
        <br>

        <button type="submit">Actualizar editorial</button>
    </form>
@endsection

Tareas/libreria/resources/views/editoriales/index.blade.php
@extends('layout.main')
@section('content')
<style>
    body{
        width: 100%;
        display: flex;
        flex-direction: column;
    }
    table {
        border-collapse: collapse;
        width: 60%;
        margin-bottom: 10px;
    }

    td,
    th {
        border: 1px solid #666666;
        padding: 2px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #dddddd;
    }

    a {
        display: inline-block;
        padding: 8px 16px;
        color: #333333;
        text-decoration: none;
        border: 1px solid #333333;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

    a:hover {
        background-color: #333;
        color: #ffffff;
    }

    button {
        padding: 8px 16px;
        color: #ffffff;
        background-color: #333;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s, color 0.3s;
    }

    button:hover {
        background-color: #666666;
    }
</style>

<body>
    <div>
    <table>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Operación</th>
        </tr>
        @foreach ($editoriales as $editorial)
        <tr>
            <td>{{$editorial->id}}</td>
            <td>{{$editorial->nombre}}</td>
            <td>
                <a href="{{ route('editoriales.edit', $editorial->id) }}">Editar</a>
                <form action="{{ route('editoriales.destroy', $editorial->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar este participante?')">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    </div>
    <div>
    <a href="{{ route('editoriales.create') }}">Crear nueva ciudad</a>
    </div>
</body>
@endsection

Tareas/libreria/resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .container {
            display: flex;
            height: 100vh;
        }

        .sidebar {
            width: 20%;
            background-color: #343a40;
            height: 100vh;
            padding: 20px 0;

        }

        .sidebar h2 {
            color: #f8f9fa;
            padding: 0 20px;
            margin-bottom: 20px;
        }

        .sidebar ul {
            list-style-type: none;
            padding: 0;
        }

        .sidebar ul li a {
            display: block;
            padding: 10px 20px;
            color: #f8f9fa;
            text-decoration: none;
        }

        .sidebar ul li a:hover {
            background-color: #495057;
        }

        .main-content {
            width: 100%;
            padding-left: 50px;
            box-sizing: border-box;
            justify-content: center;

        }
    </style>
</head>

<body>
    <div class="container">
        <div class="sidebar">
            <h2>Menú</h2>
            <ul>
                <li><a href="libros">libros</a></li>
                <li><a href="editoriales">editoriales</a></li>
            </ul>
        </div>
        <div class="main-content">
            @yield('content')
        </div>
    </div>
</body>

</html>

Tareas/libreria/resources/views/libros/create.blade.php
@extends('layout.main')

@section('content')
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="{{ route('libros.store') }}" method="post">
        @csrf
        <label for="titulo">Titulo</label>
        <input type="text" name="titulo">
        <br>
        <label for="editorial">Editorial</label>
        <select name="editorial_id" id="editorial">
            @foreach ($editoriales as $editorial)
            <option value="{{ $editorial->id }}">{{ $editorial->nombre }}</option>
            @endforeach
        </select>
        <br>
        <label for="edicion">Edicion</label>
        <input type="number" name="edicion" id="edicion">
        <br>

        <label for="pais">Pais</label>
        <input type="text" name="pais" id="pais">
        <br>
        <label for="precio">Precio</label>
        <input type="number" name="precio" id="precio">
        <br>
        
        <button type="submit">Guardar</button>
    </form>
@endsection

Tareas/libreria/resources/views/libros/edit.blade.php
@extends('layout.main')

@section('content')
    <h1>Editar Libro</h1>

    <form action="{{ route('libros.update', $libro->id) }}" method="POST">
        @csrf
        @method('PUT')

        <label for="Titulo">Titulo:</label>
        <input type="text" value="{{ $libro->titulo }}" name="titulo" id="titulo">
        <br>

        <label for="editorial">Editorial:</label>
        <select name="editorial_id" id="editorial">
            @foreach ($editoriales as $editorial)
            <option value="{{ $editorial->id }}" @selected($editorial->id==$libro->editorial_id) >{{$editorial->nombre}}</option>
            @endforeach
        </select>   
        <br>

        <label for="edicion">Edicion:</label>
        <input type="number" value="{{ $libro->edicion }}"name="edicion" id="edicion">
        <br>

        <label for="pais">Pais:</label>
        <input type="text"  value="{{ $libro->pais }}"name="pais" id="pais">
        <br>

        <label for="precio">Precio:</label>
        <input type="number"  value="{{ $libro->precio }}"name="precio" id="precio">
        <br>
        
        <button type="submit">Actualizar libro</button>
    </form>
@endsection

Tareas/libreria/resources/views/libros/index.blade.php
@extends('layout.main')

@section('content')
<style>
    body{
        display: flex;
        flex-direction: column;
    }
    table {
        border-collapse: collapse;
        width: 80%;
    }

    td,
    th {
        border: 1px solid #dddddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    a {
        display: inline-block;
        padding: 8px 16px;
        color: #333;
        text-decoration: none;
        border: 1px solid #333;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

    a:hover {
        background-color: #333;
        color: #fff;
    }

    button {
        padding: 8px 16px;
        color: #fff;
        background-color: #333;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s, color 0.3s;
    }

    button:hover {
        background-color: #666;
    }
</style>

<body>
    <div>
    <table>
        <tr>
            <th>Id</th>
            <th>Titulo</th>
            <th>Editorial</th>
            <th>Edicion</th>
            <th>Pais</th>
            <th>Precio</th>
            <th>Operación</th>
        </tr>
        @foreach ($libros as $libro)
        <tr>
            <td>{{$libro->id}}</td>
            <td>{{$libro->titulo}}</td>
            <td>
                @if ($libro->editorial)
                {{$libro->editorial->nombre}}
                @else
                Not Available
                @endif
            </td>
            <td>{{$libro->edicion}}</td>
            <td>{{$libro->pais}}</td>
            <td>{{$libro->precio}}</td>

            <td>
                <a href="{{ route('libros.edit', $libro->id) }}">Editar</a>
                <form action="{{ route('libros.destroy', $libro->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar este participante?')">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    </div>
    <div>
    <a href="{{ route('libros.create') }}">Crear nuevo participante</a>
    </div>
</body>
@endsection