Tareas/ccbol-app/routes/web.php
<?php

use App\Http\Controllers\CiudadController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ParticipanteController;


Route::resource('participantes', ParticipanteController::class);
Route::resource('ciudades', CiudadController::class)->parameters([
    'ciudades' => 'ciudad' // Aquí cambiamos 'ciudades' por 'ciudad'
]);
Route::view('/', 'layout.main')->name('home');

Tareas/ccbol-app/app/Models/Ciudad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ciudad extends Model
{
    use HasFactory;
    protected $table = 'ciudades';
    protected $fillable = ['id','nombre'];
    public function participantes()
    {
        return $this->hasMany(Participante::class);
    }
}

Tareas/ccbol-app/app/Models/Participante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Participante extends Model
{
    use HasFactory;
    protected $fillable=['carnet_identidad','nombres','apellidos','sexo','direccion','correo','celular','ciudad_id'];
    public function ciudad()
    {
        //relacion con el modelo ciudad          estandar
        return $this->belongsTo(Ciudad::class, 'ciudad_id','id');
    }
}

Tareas/ccbol-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

Tareas/ccbol-app/app/Http/Controllers/CiudadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ciudad;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CiudadController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $ciudades = Ciudad::all();
        return view('ciudades.index',['ciudades'=>$ciudades]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('ciudades.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        Ciudad::create($request->all());
        return redirect()->route('ciudades.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Ciudad $ciudad)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Ciudad $ciudad)
    {
        return view('ciudades.edit',['ciudad'=>$ciudad]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Ciudad $ciudad)
    {
        $ciudad->update($request->all());
        return redirect()->route('ciudades.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Ciudad $ciudad)
    {
        $ciudad->delete();
        return redirect()->route('ciudades.index'); 
    }
}

Tareas/ccbol-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

Tareas/ccbol-app/app/Http/Controllers/ParticipanteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Participante;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Ciudad;
use GuzzleHttp\Promise\Create;

class ParticipanteController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $participantes = Participante::with('ciudad')->get();
        return view('participantes.index',['participantes'=>$participantes]);

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $ciudades = Ciudad::all();
        return view('E.create', ['ciudades' => $ciudades]);
    }
    
    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //depurar y ver valores
        // dd($request->all());
        Participante::create($request->all());
        return redirect()->route('participantes.index');

  
    }

    /**
     * Display the specified resource.
     */
    public function show(Participante $participante)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Participante $participante)
    {
        // Muestra los valores del objeto
        // dd($participante);
        $ciudades = Ciudad::all();
        return view('participantes.edit', ['participante' => $participante], ['ciudades' => $ciudades]);
    }
    

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Participante $participante)
    {
        $participante->update($request->all());
        return redirect()->route('participantes.index')->with('success', 'Participante actualizado correctamente.');
    }
    

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Participante $participante)
    {
   // Elimina el participante de la base de datos
   $participante->delete();
    
   // Redirecciona a la página index con un mensaje de éxito
   return redirect()->route('participantes.index')->with('success', 'Participante eliminado correctamente.');    }
}

Tareas/ccbol-app/resources/views/ciudades/create.blade.php
@extends('layout.main')

@section('content')
    <form action="{{ route('ciudades.store') }}" method="post">
        @csrf
        <label for="nombre">nombre</label>
        <input type="text" name="nombre">
        <br>
        <button type="submit">Guardar</button>
    </form>
@endsection

Tareas/ccbol-app/resources/views/ciudades/edit.blade.php
@extends('layout.main')

@section('content')
    <h1>Editar Ciudad</h1>

    <form action="{{ route('ciudades.update', $ciudad->id) }}" method="POST">
        @csrf
        @method('PUT')

        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" id="nombre" value="{{ $ciudad->nombre }}">
        <br>

        <button type="submit">Actualizar Ciudad</button>
    </form>
@endsection

Tareas/ccbol-app/resources/views/ciudades/index.blade.php
@extends('layout.main')
@section('content')
<style>
    body{
        width: 100%;
        display: flex;
        flex-direction: column;
    }
    table {
        border-collapse: collapse;
        width: 60%;
        margin-bottom: 10px;
    }

    td,
    th {
        border: 1px solid #666666;
        padding: 2px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #dddddd;
    }

    a {
        display: inline-block;
        padding: 8px 16px;
        color: #333333;
        text-decoration: none;
        border: 1px solid #333333;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

    a:hover {
        background-color: #333;
        color: #ffffff;
    }

    button {
        padding: 8px 16px;
        color: #ffffff;
        background-color: #333;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s, color 0.3s;
    }

    button:hover {
        background-color: #666666;
    }
</style>

<body>
    <div>
    <table>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Operación</th>
        </tr>
        @foreach ($ciudades as $ciudad)
        <tr>
            <td>{{$ciudad->id}}</td>
            <td>{{$ciudad->nombre}}</td>
            <td>
                <a href="{{ route('ciudades.edit', $ciudad->id) }}">Editar</a>
                <form action="{{ route('ciudades.destroy', $ciudad->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar este participante?')">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    </div>
    <div>
    <a href="{{ route('ciudades.create') }}">Crear nueva ciudad</a>
    </div>
</body>
@endsection

Tareas/ccbol-app/resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .container {
            display: flex;
            height: 100vh;
        }

        .sidebar {
            width: 20%;
            background-color: #343a40;
            height: 100vh;
            padding: 20px 0;

        }

        .sidebar h2 {
            color: #f8f9fa;
            padding: 0 20px;
            margin-bottom: 20px;
        }

        .sidebar ul {
            list-style-type: none;
            padding: 0;
        }

        .sidebar ul li a {
            display: block;
            padding: 10px 20px;
            color: #f8f9fa;
            text-decoration: none;
        }

        .sidebar ul li a:hover {
            background-color: #495057;
        }

        .main-content {
            width: 100%;
            padding-left: 50px;
            box-sizing: border-box;
            justify-content: center;

        }
    </style>
</head>

<body>
    <div class="container">
        <div class="sidebar">
            <h2>Menú</h2>
            <ul>
                <li><a href="ciudades">Ciudades</a></li>
                <li><a href="participantes">Participantes</a></li>
            </ul>
        </div>
        <div class="main-content">
            @yield('content')
        </div>
    </div>
</body>

</html>

Tareas/ccbol-app/resources/views/participantes/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="{{ route('participantes.store') }}" method="post">
        @csrf
        <label for="carnet_identidad">Carnet de identidad</label>
        <input type="text" name="carnet_identidad">
        <br>
        <label for="nombres">Nombres</label>
        <input type="text" name="nombres" id="nombres">
        <br>
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" id="apellidos">
        <br>
        <label for="sexo">Sexo</label>
        <input type="radio" name="sexo" id="F" value="F">M
        <input type="radio" name="sexo" id="M" value="M">F
        <br>
        <label for="direccion">Dirección</label>
        <input type="text" name="direccion" id="direccion">
        <br>
        <label for="correo">Correo</label>
        <input type="email" name="correo" id="correo">
        <br>
        <label for="celular">Celular</label>
        <input type="text" name="celular" id="celular">
        <br>
        <label for="ciudad">Ciudad</label>
        <select name="ciudad_id" id="ciudad">
            @foreach ($ciudades as $ciudad)
            <option value="{{ $ciudad->id }}">{{ $ciudad->nombre }}</option>
            @endforeach
        </select>
        <br>
        <button type="submit">Guardar</button>
    </form>
@endsection

Tareas/ccbol-app/resources/views/participantes/edit.blade.php
@extends('layout.main')

@section('content')
    <h1>Editar Participante</h1>

    <form action="{{ route('participantes.update', $participante->id) }}" method="POST">
        @csrf
        @method('PUT')

        <label for="nombres">Nombres:</label>
        <input type="text" name="nombres" id="nombres" value="{{ $participante->nombres }}">
        <br>

        <label for="apellidos">Apellidos:</label>
        <input type="text" name="apellidos" id="apellidos" value="{{ $participante->apellidos }}">
        <br>

        <label>Sexo:</label>
        <input type="radio" name="sexo" id="F" value="F" @checked($participante->sexo=='F')>
        <label for="F">F</label>
        <input type="radio" name="sexo" id="M" value="M" @checked($participante->sexo=='M')>
        <label for="M">M</label>
        <br>

        <label for="direccion">Dirección:</label>
        <input type="text" name="direccion" id="direccion" value="{{ $participante->direccion }}">
        <br>

        <label for="correo">Correo Electrónico:</label>
        <input type="email" name="correo" id="correo" value="{{ $participante->correo }}">
        <br>

        <label for="celular">Celular:</label>
        <input type="text" name="celular" id="celular" value="{{ $participante->celular }}">
        <br>

        <label for="ciudad">Ciudad:</label>
        <select name="ciudad_id" id="ciudad">
            @foreach ($ciudades as $ciudad)
            <option value="{{ $ciudad->id }}" @selected($ciudad->id==$participante->ciudad_id) >{{$ciudad->nombre}}</option>
            @endforeach
        </select>   
        <br>

        <button type="submit">Actualizar Participante</button>
    </form>
@endsection

Tareas/ccbol-app/resources/views/participantes/index.blade.php
@extends('layout.main')

@section('content')
<style>
    body{
        display: flex;
        flex-direction: column;
    }
    table {
        border-collapse: collapse;
        width: 80%;
    }

    td,
    th {
        border: 1px solid #dddddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    a {
        display: inline-block;
        padding: 8px 16px;
        color: #333;
        text-decoration: none;
        border: 1px solid #333;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

    a:hover {
        background-color: #333;
        color: #fff;
    }

    button {
        padding: 8px 16px;
        color: #fff;
        background-color: #333;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s, color 0.3s;
    }

    button:hover {
        background-color: #666;
    }
</style>

<body>
    <div>
    <table>
        <tr>
            <th>Id</th>
            <th>Carnet de Identidad</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Sexo</th>
            <th>Dirección</th>
            <th>Correo Electrónico</th>
            <th>Celular</th>
            <th>Ciudad</th>
            <th>Operación</th>
        </tr>
        @foreach ($participantes as $participante)
        <tr>
            <td>{{$participante->id}}</td>
            <td>{{$participante->carnet_identidad}}</td>
            <td>{{$participante->nombres}}</td>
            <td>{{$participante->apellidos}}</td>
            <td>{{$participante->sexo}}</td>
            <td>{{$participante->direccion}}</td>
            <td>{{$participante->correo}}</td>
            <td>{{$participante->celular}}</td>
            <td>
                @if ($participante->ciudad)
                {{$participante->ciudad->nombre}}
                @else
                Not Available
                @endif
            </td>
            <td>
                <a href="{{ route('participantes.edit', $participante->id) }}">Editar</a>
                <form action="{{ route('participantes.destroy', $participante->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar este participante?')">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    </div>
    <div>
    <a href="{{ route('participantes.create') }}">Crear nuevo participante</a>
    </div>
</body>
@endsection